### PR TITLE
Add screenshot + instructions + example

### PR DESCRIPTION
**Pull request by dciccale**
Waiting for this PR that includes the screenshot https://github.com/dracula/dracula.github.io/pull/1 :)

### CODE REVIEW

**Comment by nesl247** [comment]
At the moment we actually want the instructions to be on the site instead of on the individual theme repos. The ones that have the instructions are ones without a site entry at the moment. The plan is to eventually build the site using the READMEs of the theme repos though.

Could you please do a PR against the site `dracula.github.io` with the instructions instead? If you look at https://github.com/dracula/template/blob/master/README.md you can see the template for linking to the site.

Thanks!

**Comment by dciccale** [comment]
OK, however I do not have a cool icon to include in the website :(

nevertheless I will write the docs on `dracula.github.io` and link to it :)

**Comment by nesl247** [comment]
I wouldn't even worry about the site right now. We're going to be redoing the way the site is built (we're going to pull the README.md in from each repo), so having the instructions in the README is perfectly fine.

Sorry for the confusion, we've been re-strategizing the migration, so we've gone back and forth a few times. We've settled on the plan though.

**Comment by nesl247** [comment]
Could you please shorten the example code up to just a few lines of JS to be highlighted and only the minimal HTML required? The screenshot shows the result really well I think. Also, I wouldn't use Example as the header as it's really just an example for the installation instructions. I would probably just remove that header all together.

**Comment by dciccale** [comment]
woops, I also added the team, I guess it shold be only me for now

**Comment by dciccale** [comment]
could you please cleanup the team section then ?

**Comment by nesl247** [comment]
Thanks. I've fixed the team section for you as well.

**Pull request merged**
